// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PSAAS.Infrastructure.Data.DbContexts;

#nullable disable

namespace PSAAS.Infrastructure.Data.Migrations
{
    [DbContext(typeof(PsaasDbContext))]
    partial class PsaasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PSAAS.Infrastructure.Data.DbModels.ProductiveUnitDbModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProfileId");

                    b.HasIndex("TenantId");

                    b.ToTable("ProductiveUnits", (string)null);
                });

            modelBuilder.Entity("PSAAS.Infrastructure.Data.DbModels.ProfileDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles", (string)null);
                });

            modelBuilder.Entity("PSAAS.Infrastructure.Data.DbModels.TenantDbModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("CertifiedEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompleteVatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VatNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CertifiedEmail")
                        .IsUnique();

                    b.HasIndex("CompleteVatNumber")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("VatNumber")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("PSAAS.Infrastructure.Data.DbModels.ProductiveUnitDbModel", b =>
                {
                    b.HasOne("PSAAS.Infrastructure.Data.DbModels.ProfileDbModel", "Profile")
                        .WithMany("ProductiveUnits")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PSAAS.Infrastructure.Data.DbModels.TenantDbModel", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PSAAS.Infrastructure.Data.DbModels.TenantDbModel", b =>
                {
                    b.OwnsOne("PSAAS.Domain.Address", "Address", b1 =>
                        {
                            b1.Property<string>("TenantDbModelId");

                            b1.Property<string>("city")
                                .IsRequired();

                            b1.Property<string>("country")
                                .IsRequired();

                            b1.Property<string>("postalCode")
                                .IsRequired();

                            b1.Property<string>("street")
                                .IsRequired();

                            b1.HasKey("TenantDbModelId");

                            b1.ToTable("Tenants");

                            b1.ToJson("Address");

                            b1.WithOwner()
                                .HasForeignKey("TenantDbModelId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("PSAAS.Infrastructure.Data.DbModels.ProfileDbModel", b =>
                {
                    b.Navigation("ProductiveUnits");
                });
#pragma warning restore 612, 618
        }
    }
}
