<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Infrastructure\PSAAS.Domain\PSAAS.Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\PSAAS.Infrastructure\PSAAS.Infrastructure.csproj" />
    <ProjectReference Include="..\PSAAS.Auth\PSAAS.Auth.csproj" />
  </ItemGroup>

</Project>
